[workspace]
resolver = "2"
members = ["examples/hedra-triangle", "hedra"]

[profile.dev]
opt-level = 0
overflow-checks = true
lto = false
panic = "abort"

[profile.release]
opt-level = 3
overflow-checks = false
lto = true
panic = "unwind"
